---
# tasks file for centralServer
- name: disable default route
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no
    
- name: add default gateway for centralServer
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.0.1
    
- name: set up route on centralServer eth1
  template:
    src: route-eth1
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
